[tool.poetry]
name = "garbanzo"
version = "0.1.0"
description = ""
authors = ["Jeremy Silver <jeremys@nessiness.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
